engines:
- name: duckduckgo
- engine: wikipedia
  name: wikipedia
- engine: wikidata
  name: wikidata
general:
  debug: false
  enable_metrics: false
  instance_name: SearXNG + MCP
limiter: false
outgoing:
  max_request_timeout: 30.0
  number_of_retries: 2
  proxies:
    http:
    - http://127.0.0.1:7897
    https:
    - http://127.0.0.1:7897
  request_timeout: 30.0
result_formats:
  csv: true
  html: true
  json: true
  rss: true
search:
  autocomplete: ''
  formats:
  - html
  - json
  - csv
  max_results: 20
  min_length_of_query: 3
  safe_search: 0
server:
  bind_address: 127.0.0.1
  http_protocol_version: '1.1'
  method: GET
  port: 3001
  secret_key: edcad06945e4696ae95c9e4a2bb4ac92242b4be00a41286ad73753c3d34b3df4
ui:
  infinite_scroll: true
  results_on_new_tab: false
  theme_args:
    simple_style: auto
use_default_settings: true
